<table class="services">
	<tr>
		<th>Host</th>
		<th width="10%">State</th>
		<th width="20%">Service</th>
		<th width="20%">Last check</th>
	</tr>
	<?php foreach ($this->oView->aServices as $sHostName => $aServices): ?>
		<?php $iServiceCount = 0; ?>
		<?php foreach ($aServices as $aService): ?>
		<tr>
			<?php if ($iServiceCount === 0): ?>
			<td class="host_name" rowspan="<?= count($aServices) ?>"><?= htmlspecialchars($sHostName); ?></td>
			<?php endif; ?>

			<td class="state_<?= strtolower($aService['last_state']); ?>"><?= htmlspecialchars($aService['last_state']); ?></td>
			<td><a href="/service/detail/?service_id=<?= $aService['hs_id'] ?>"><?= htmlspecialchars($aService['service_name']); ?></a></td>
			<td><?= htmlspecialchars($aService['last_run']); ?></td>

			<?php $iServiceCount++; ?>
		</tr>
		<?php endforeach; ?>
	<?php endforeach; ?>
</table>